server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/beatCoin
    username: postgres
    password: Andy1964
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5433/beatCoin
    user: postgres
    password: Andy1964
    driver-class-name: org.postgresql.Driver

app:
  rest:
    api:
      prefix: /api

  telegram:
    url: https://api.telegram.org
    refresh-rate-ms: 3000